### ISSUE TITLE
Deprecated Health Check

### ISSUE THREAD

**Issue by voltechs** [newrelic/nri-rabbitmq#52]
##### Description of the problem

RabbitMQ has deprecated the **`node_health_check`** endpoint.

```log
2020-07-06 17:58:56.797 [warning] <0.13613.0> rabbitmqctl node_health_check and its HTTP API counterpart are DEPRECATED. See https://www.rabbitmq.com/monitoring.html#health-checks for replacement options.
```

[Other projects](https://github.com/helm/charts/issues/23083) are looking into this. [@vermaabhay](https://github.com/vermaabhay) suggest:

> I think "rabbitmq-diagnostics -q check_port_connectivity" should be sufficient for checking node health as liveliness and readiness probe in K8s.
> 
> RabbitMQ team discourages using "rabbitmqctl node_health_check". As "rabbitmqctl node_health_check" requires a fully booted node so if a node is waiting for a peer to appear to sync tables from, it cannot succeed and eventually enters into a node restart deadlock. Also, management health check doesn't work correctly on a heavily loaded node.

It appears these lines would need to change
https://github.com/newrelic/nri-rabbitmq/blob/2d4cf446bd1d22187ffc26f268dc31ae9f02445c/src/rabbitmq.go#L53
https://github.com/newrelic/nri-rabbitmq/blob/6f846ef64db606969dee11c4aede89681bf69b84/src/client/client.go#L34-L35
Including tests, here:
https://github.com/newrelic/nri-rabbitmq/blob/0c679b1af79547f176363dba5e57073c0d10a7ff/src/rabbitmq_test.go#L23
https://github.com/newrelic/nri-rabbitmq/blob/0c679b1af79547f176363dba5e57073c0d10a7ff/src/rabbitmq_test.go#L73

##### OS

- [x] All of them

**Comment by camdencheek** [comment]
Hi @voltechs -- thanks for the report! I'll try to find some time to take a closer look at fixing this. Otherwise, I'm happy to take a PR

**Comment by michaelklishin** [comment]
The new health check endpoints have been out for a year if not more now. The deprecation note has been [officially put into the Monitoring guide](https://www.rabbitmq.com/monitoring.html#health-checks) for months, too. Would be nice to see
this monitoring agent switch over some time soon.

**Comment by kloarubeek** [comment]
when can we expect this to be released? Using the old healthchecks really fills up the Rabbit node logs 😞.

**Comment by alvarocabanas** [comment]
In our actual integration we are calling the deprecated `GET /api/health/checks/node/{node}`and this allows us to only require from the user the host and port from the master node as it's able to get the healthchecks from the rest of the nodes.

The new healthcheck endpoint `GET /api/health/checks/*` only checks health for the node where it's called. The master's api is not capable of getting the host:port of each member, so we need to decide if we add a new configuration flag so the user can specify all the nodes `host:port` in the cluster to do the health check.

Here they defined all the constraints for the new endpoints before implementing them:
https://github.com/rabbitmq/rabbitmq-management/issues/844

**Comment by michaelklishin** [comment]
@alvarocabanas there are no "master" nodes in RabbitMQ. Perhaps you are referring to some concept in New Relic agents that I'm not aware of.

The old, intrusive One True Health Check™ did not perform a check on all nodes. Or rather, some checks did involve interaction with other nodes but not all. In general, one node
cannot health check the entire cluster: it might not be able to connect to its peers, it
would not make much sense to expose every single piece of state to such "remote checks", and so on.

Finally, the approach to checks we've had since 2020 fits how monitoring is done in many systems: each node reports its own stats, and monitoring tools do the aggregation.

**Comment by michaelklishin** [comment]
Modern health checks have a separate [section in the docs](https://www.rabbitmq.com/monitoring.html#health-checks). There's also another one that discusses what health checks can or cannot be used as [readiness probes](https://www.rabbitmq.com/monitoring.html#readiness-probes).

**Comment by alvarocabanas** [comment]
Hi @michaelklishin, yes, I know Rabbitmq doesn't have the concept of a master node, what I meant with master is the node where we are getting all the cluster metrics from its API. 
The integration then produces all the entities of all the nodes and adds the metrics. 
A part from metric collection, there is events that show healthcheck and aliveness on the nodes, and the node healthchecks are calculated with the old endpoint, all collected from the same node, so, if we need to call each node separately, we then need the host:port of each node to get the healthcheck from its api.
Are you telling me that you are setting one instance for each node? And aren't you getting duplicated date if they are in the same cluster?
One possibility we can do is to remove completely the information of other nodes in the integration and make it mandatory to have one instance to only get data from that specific node. Then we would document that each node needs its own instance.

**Comment by michaelklishin** [comment]
With Prometheus, every node serves its own stats. With HTTP API, every node can serve metrics of every other node. The Prometheus endpoint is much more difficult to mis-use and is highly recommended for many reasons.

And yes, you would need a list of cluster nodes in order to migrate to it. The port is usually the same on all of them.

**Comment by jcardenas9x** [comment]
The deprecation warning is polluting the RabbitMQ logs, so is there a method to suppress or stop the health check function from being invoked? I don't want to rely on waiting for an update that fixes this issue to be released.

**Comment by michaelklishin** [comment]
> The deprecation warning is polluting the RabbitMQ logs, so is there a method to suppress or stop the health check function from being invoked? I don't want to rely on waiting for an update that fixes this issue to be released.

Most likely your best short term bet would be to raise the log level so that warnings are not logged at all. Some warnings would be very useful to spot early (e.g. those about [abrupt TCP connection closures by clients](https://www.rabbitmq.com/logging.html#connection-lifecycle-events)) but most are, well, warnings.

**Comment by yusuf-comez-mackolik** [comment]
It is over 2 years and this issue is still open, this is really interesting. We are using New Relic, monitoring tonnes of servers & services. We also are transferring our logs to New Relic and for sure we pay for all of these. In 24 hours, our logs are filled with 240k records just because of this deprecation warning. And obviously, we don't want to turn off warnings. Should I get a discount for 7.2 millions of records for a month? :)

Guys, 2 years, really? :)

**Comment by mangulonr** [comment]
Hi Yusuf

Sorry for the inconveniences on the delay of this task.
There aren't excuses to delay this issue for such a long time.

This task was finally prioritized 2 weeks ago. 
As you can see in the issue we will work on it during the Sprint happening between Sep 26 and  Oct 7, 2022.

Regards
